# Generated by Django 3.2.4 on 2021-11-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_auto_20211030_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acmcontestrank',
            old_name='total_score',
            new_name='total_penalty',
        ),
    ]
