# Generated by Django 3.2.12 on 2022-03-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_rename_total_score_acmcontestrank_total_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='constraints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contest',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoring',
            field=models.TextField(default='ACM-ICPC style'),
        ),
        migrations.CreateModel(
            name='ContestPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField()),
                ('name', models.TextField()),
                ('reward', models.TextField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
        ),
        migrations.AddField(
            model_name='acmcontestrank',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contestprize'),
        ),
        migrations.AddField(
            model_name='oicontestrank',
            name='prize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contestprize'),
        ),
    ]
