# Generated by Django 3.2.4 on 2021-12-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20211030_1535'),
        ('contest', '0012_rename_total_score_acmcontestrank_total_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestannouncement',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
    ]
