# Generated by Django 3.2.10 on 2022-01-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '__first__'),
        ('contest', '0012_rename_total_score_acmcontestrank_total_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestannouncement',
            name='problem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
    ]
