# Generated by Django 3.2.12 on 2022-02-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_is_admin_groupmember_is_group_admin'),
        ('contest', '0013_contestannouncement_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allowed_groups',
            field=models.ManyToManyField(to='group.Group'),
        ),
        migrations.AddField(
            model_name='contest',
            name='prize',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoring',
            field=models.TextField(default='ACM-ICPC style'),
        ),
    ]
