# Generated by Django 3.2.12 on 2022-03-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_contestannouncement_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='bank_filter',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='is_bank',
            field=models.BooleanField(default=False),
        ),
    ]
