# Generated by Django 3.2.12 on 2022-02-10 16:09

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_contestannouncement_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='prize',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='contest',
            name='requirements',
            field=utils.models.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='scoring',
            field=models.TextField(default='ACM-ICPC style'),
        ),
    ]
