# Generated by Django 3.2.12 on 2022-02-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20220211_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='constraints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contest',
            name='requirements',
            field=models.JSONField(default=list),
        ),
    ]
