# Generated by Django 3.2.12 on 2022-02-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_is_admin_groupmember_is_group_admin'),
        ('contest', '0014_auto_20220211_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='allowed_groups',
            field=models.ManyToManyField(to='group.Group'),
        ),
        migrations.AddField(
            model_name='contest',
            name='constraints',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='requirements',
            field=models.JSONField(null=True),
        ),
    ]
