# Generated by Django 3.2.12 on 2022-03-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_problembank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_bank',
        ),
    ]
