# Generated by Django 3.2.12 on 2022-02-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_auto_20220211_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='prize',
            new_name='prizes',
        ),
    ]
