# Generated by Django 3.2.12 on 2022-02-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_rename_is_admin_groupmember_is_group_admin'),
        ('contest', '0016_rename_prize_contest_prizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, to='group.Group'),
        ),
    ]
