# Generated by Django 3.2.12 on 2022-02-25 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_auto_20220225_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestprize',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='contest.contest'),
        ),
    ]
