# Generated by Django 3.2.12 on 2022-03-15 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0019_alter_contestprize_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='bank_filter',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='ProblemBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_list', models.TextField(null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_bank',
                'unique_together': {('user', 'contest')},
            },
        ),
    ]
