# Generated by Django 3.2.12 on 2022-03-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_remove_contest_is_bank'),
        ('contest', '0019_alter_contestprize_contest'),
    ]

    operations = [
    ]
