# Generated by Django 3.2.12 on 2022-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_auto_20220315_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='rank_penalty_visible',
            field=models.BooleanField(default=True),
        ),
    ]
