gitConfig:
  pull.rebase: "true"

ports:
  - port: 8080 # Vue CLI
    onOpen: ignore
  - port: 8000 # Django runserver
    onOpen: ignore
    visibility: public
  - port: 3000 # Vite
    onOpen: ignore
  - port: 5432 # PostgreSQL
    onOpen: ignore
  - port: 6379 # Redis
    onOpen: ignore

tasks:
  - name: Node.js
    init: yarn --cwd /workspace/skku-coding-platform/frontend/ install

  - name: Python
    init: |
      pip freeze | xargs pip uninstall -y
      pip install -r /workspace/skku-coding-platform/backend/deploy/requirements.txt

  - name: DB Container
    command: docker-compose -f /workspace/skku-coding-platform/.gitpod.docker-compose.yml up -d

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - eamodio.gitlens
    - editorconfig.editorconfig
    - gruntfuggly.todo-tree
    - humao.rest-client
    - johnsoncodehk.volar
    - ms-azuretools.vscode-docker
    - ms-python.python
    - naumovs.color-highlight
    - oderwat.indent-rainbow
    - pkief.material-icon-theme
