gitConfig:
  pull.rebase: "true"

ports:
  - port: 8080
    onOpen: ignore
  - port: 5435
    onOpen: ignore
  - port: 6380
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore

tasks:
  - name: Install frontend packages
    init: yarn --cwd /workspace/skku-coding-platform/frontend/ install

  - name: Install backend packages
    init: python3 -m pip install -r /workspace/skku-coding-platform/backend/deploy/requirements.txt

vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - donjayamanne.githistory
    - eamodio.gitlens
    - editorconfig.editorconfig
    - gruntfuggly.todo-tree
    - humao.rest-client
    - ms-azuretools.vscode-docker
    - ms-python.python
    - naumovs.color-highlight
    - oderwat.indent-rainbow
    - pkief.material-icon-theme
