# Generated by Django 3.2.9 on 2022-01-01 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('path', models.TextField()),
                ('visible', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'banner',
                'ordering': ('-create_time',),
            },
        ),
    ]
