# Generated by Django 2.2.24 on 2021-08-08 08:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Takes',
            new_name='Registration',
        ),
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
