# Generated by Django 3.2.5 on 2021-12-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211226_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bookmark',
            field=models.BooleanField(default=True),
        ),
    ]
