# Generated by Django 2.2.24 on 2021-07-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
        ('submission', '0012_auto_20180501_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
