# Generated by Django 3.2.12 on 2022-02-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_submission_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
