# Generated by Django 2.2.24 on 2021-08-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0014_auto_20210802_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
    ]
