# Generated by Django 3.2.12 on 2022-02-11 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_registration_bookmark'),
        ('submission', '0016_auto_20211226_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='course.course'),
        ),
    ]
