# Generated by Django 3.2.12 on 2022-03-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0016_auto_20211226_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
