# Generated by Django 2.1.7 on 2021-01-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210117_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_auth_token',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_email_auth',
            field=models.BooleanField(default=True),
        ),
    ]
