# Generated by Django 2.2.24 on 2021-07-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210126_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tfa_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='two_factor_auth',
        ),
    ]
