# Generated by Django 2.2.24 on 2021-07-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20210703_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='open_api',
        ),
        migrations.RemoveField(
            model_name='user',
            name='open_api_appkey',
        ),
    ]
