# Generated by Django 2.2.24 on 2021-07-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210703_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mood',
        ),
    ]
