# Generated by Django 3.2.5 on 2021-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_alter_announcement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='top_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
