from django.urls import include, path


urlpatterns = [
    path("api/", include("account.urls.oj")),
    path("api/admin/", include("account.urls.admin")),
    path("api/", include("announcement.urls.oj")),
    path("api/admin/", include("announcement.urls.admin")),
    path("api/", include("conf.urls.oj")),
    path("api/admin/", include("conf.urls.admin")),
    path("api/", include("problem.urls.oj")),
    path("api/admin/", include("problem.urls.admin")),
    path("api/", include("contest.urls.oj")),
    path("api/admin/", include("contest.urls.admin")),
    path("api/", include("submission.urls")),
    path("api/admin/", include("utils.urls")),
    url(r"^swagger/$", schema_view.with_ui("swagger", cache_timeout=0), name="schema-swagger-ui"),
    url(r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    url(r"^api/", include("account.urls.oj")),
    url(r"^api/admin/", include("account.urls.admin")),
    url(r"^api/", include("announcement.urls.oj")),
    url(r"^api/admin/", include("announcement.urls.admin")),
    url(r"^api/", include("conf.urls.oj")),
    url(r"^api/admin/", include("conf.urls.admin")),
    url(r"^api/", include("problem.urls.oj")),
    url(r"^api/admin/", include("problem.urls.admin")),
    url(r"^api/lecture/", include("problem.urls.student")),
    url(r"^api/lecture/professor/", include("problem.urls.professor")),
    url(r"^api/", include("contest.urls.oj")),
    url(r"^api/admin/", include("contest.urls.admin")),
    url(r"^api/", include("submission.urls")),
    url(r"^api/admin/", include("utils.urls")),
    url(r"^api/lecture/", include("course.urls.student")),
    url(r"^api/lecture/professor/", include("course.urls.professor")),
    url(r"^api/lecture/", include("assignment.urls.student")),
    url(r"^api/lecture/professor/", include("assignment.urls.professor")),
]
