# Generated by Django 2.1.7 on 2021-01-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='school',
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.TextField(null=True),
        ),
    ]
