# Generated by Django 3.2.11 on 2022-01-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupapplication',
            old_name='user',
            new_name='created_by',
        ),
    ]
