# Generated by Django 3.2.11 on 2022-02-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20220203_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='is_admin',
            new_name='is_group_admin',
        ),
    ]
