version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis

  judge-server-dev:
    image: skkunpc/judge-server
    container_name: judge-server-dev
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ../backend/data/test_case:/test_case:ro
      - ./judge-server/log:/log
      - ./judge-server/run:/judger

    environment:
      - SERVICE_URL=http://judge-server-dev:8080
      - BACKEND_URL=http://app:8000/api/judge_server_heartbeat/
      - TOKEN=CHANGE_THIS

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=codingplatform
      - POSTGRES_USER=codingplatform
      - POSTGRES_DB=codingplatform

  redis:
    image: redis:4.0-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data: null
  redis-data: null
