# Generated by Django 2.2.24 on 2021-07-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='content',
            new_name='description',
        ),
    ]
