# Generated by Django 3.2.10 on 2022-03-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ('-temperature',)},
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='temeperature',
            new_name='temperature',
        ),
    ]
