# Generated by Django 3.2.10 on 2022-03-15 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_auto_20220315_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('user_id', 'date')},
        ),
    ]
