# Generated by Django 3.2.10 on 2022-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0003_auto_20220315_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
