# Generated by Django 3.2.10 on 2022-03-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0004_alter_temperature_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solvedproblem',
            options={'ordering': ('-solved_time',)},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='solvedproblem',
            name='_id',
            field=models.TextField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='solvedproblem',
            name='id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solvedproblem',
            name='solved_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='solvedproblem',
            unique_together={('user_id', '_id')},
        ),
    ]
