# Generated by Django 3.2.10 on 2022-03-15 12:18

from django.db import migrations, models
import utils.shortcuts


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0005_auto_20220315_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedproblem',
            name='id',
            field=models.TextField(db_index=True, default=utils.shortcuts.rand_str, primary_key=True, serialize=False),
        ),
    ]
