# Generated by Django 3.2.10 on 2022-03-23 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20211030_1535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('temperature', '0006_alter_solvedproblem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedproblem',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='solvedproblem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temperature',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solvedproblem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='solvedproblem',
            unique_together={('user', 'problem')},
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='solvedproblem',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='solvedproblem',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='temperature',
            name='user_id',
        ),
    ]
