# Generated by Django 4.0.1 on 2022-01-09 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_registration_bookmark'),
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='question',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
