# Generated by Django 4.0.1 on 2022-01-09 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_registration_bookmark'),
        ('qna', '0002_question_content_question_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='last_update_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
    ]
