# Generated by Django 4.0.1 on 2022-01-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_alter_question_content_alter_question_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='course_id',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='question',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
