# Generated by Django 3.2.4 on 2022-02-20 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_rename_course_id_question_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='is_open',
        ),
    ]
