// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HeaderLogo: typeof import('./components/atoms/HeaderLogo.vue')['default']
    HeaderMain: typeof import('./components/organisms/HeaderMain.vue')['default']
    HeaderMobileButton: typeof import('./components/atoms/HeaderMobileButton.vue')['default']
    HeaderMobileNav: typeof import('./components/molecules/HeaderMobileNav.vue')['default']
    HeaderNav: typeof import('./components/molecules/HeaderNav.vue')['default']
    IconFaBars: typeof import('~icons/fa/bars')['default']
    NavItem: typeof import('./components/atoms/NavItem.vue')['default']
  }
}

export { }
