# Generated by Django 2.2.24 on 2021-08-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0015_auto_20210730_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='assignment.Assignment'),
        ),
    ]
