# Generated by Django 2.2.24 on 2021-08-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0016_auto_20210801_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.TextField(default='Problem', null=True),
        ),
    ]
