# Generated by Django 3.2.11 on 2022-02-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_registration_bookmark'),
        ('problem', '0018_auto_20211226_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='course.course'),
        ),
    ]
