# Generated by Django 3.2.12 on 2022-03-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0018_auto_20211226_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='bank',
            field=models.BooleanField(default=False),
        ),
    ]
