# Generated by Django 3.2.12 on 2022-03-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0019_problem_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('button_type', models.TextField()),
                ('is_disabled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('color', models.TextField()),
                ('is_disabled', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('problem_set_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_set', to='problem.problemsetgroup')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='problem.problemset'),
        ),
    ]
