# Generated by Django 3.2.12 on 2022-03-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0020_auto_20220327_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_set',
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_set',
            field=models.ManyToManyField(null=True, to='problem.ProblemSet'),
        ),
    ]
