# Generated by Django 3.2.12 on 2022-03-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0021_auto_20220329_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_set',
            field=models.ManyToManyField(blank=True, to='problem.ProblemSet'),
        ),
    ]
