# Generated by Django 3.2.12 on 2022-03-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0022_alter_problem_problem_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='problem_set',
        ),
        migrations.AddField(
            model_name='problemset',
            name='problems',
            field=models.ManyToManyField(blank=True, to='problem.Problem'),
        ),
    ]
