# Generated by Django 3.2.12 on 2022-03-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0023_auto_20220329_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='problem_set', to='problem.Problem'),
        ),
    ]
