# Generated by Django 3.2.12 on 2022-03-30 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0024_alter_problemset_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemset',
            name='problem_set_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_set', to='problem.problemsetgroup'),
        ),
    ]
